1901042695: 1901042695.o abstracthex.o hexarray1d.o hexvector.o hexadapter.o
	g++ 1901042695.o abstracthex.o hexarray1d.o hexvector.o hexadapter.o  -o 1901042695
1901042695.o: 1901042695.cpp
	g++ -c -std=gnu++11 1901042695.cpp
abstracthex.o:abstracthex.cpp
	g++ -c -std=gnu++11 abstracthex.cpp
hexarray1d.o:hexarray1d.cpp
	g++ -c -std=gnu++11 hexarray1d.cpp
hexvector.o:hexvector.cpp
	g++ -c -std=gnu++11 hexvector.cpp
hexadapter.h:
